service: mytabs-client-client

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.currentStage}
  deploymentPrefix: client
  deploymentBucket:
    name: bp-${self:custom.projectName}-deploymentbucket-${self:custom.currentStage}
    blockPublicAccess: true

custom:
  currentStage: dev
  projectName: mytabs-web
  sitename: bp-${self:service}-${self:custom.currentStage}
  s3Sync:
    - bucketName: ${self:custom.sitename}
      localDir: build

plugins:
  - serverless-s3-sync

resources:
  Resources:
    CloudfrontOAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: ${self:custom.sitename}
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        BucketName: ${self:custom.sitename}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadForGetBucketObjectsOAI
              Effect: Allow
              Principal:
                AWS: !Join ['',["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ",Ref: CloudfrontOAI]]
              Action:
                - "s3:get*"
              Resource:
                - !Join ['',["arn:aws:s3:::",Ref: StaticSite]]
                - !Join ['',["arn:aws:s3:::",Ref: StaticSite,/*]]
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
    cloudfront:
      Type: AWS::CloudFront::Distribution
      DependsOn: StaticSite
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !Join ['',[Ref: StaticSite,.s3.amazonaws.com]]
              Id: !Ref StaticSite
              S3OriginConfig:
                OriginAccessIdentity: !Join ['',["origin-access-identity/cloudfront/",Ref: CloudfrontOAI]]
          Comment: !Ref StaticSite
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: !Ref StaticSite
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad #CachingDisabled
          PriceClass: PriceClass_100
          HttpVersion: http2
          IPV6Enabled: true
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          CustomErrorResponses:
            - ErrorCachingMinTTL: 5
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCachingMinTTL: 5
              ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
  Outputs:
    AdminBucket:
      Value: !Ref StaticSite